### ISSUE TITLE
Users can view makeup products

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/ajax-project#1]
## 📐 Functionality

Users will be able to scroll through a list of beauty product that includes the product’s name, image, and price

## 🖼️ Wireframes

Mobile:
https://www.figma.com/file/FygER9DI2JeIFNgEiG4cJQ/Christina-Le---Ajax-Project?node-id=1%3A3

Desktop:
https://www.figma.com/file/FygER9DI2JeIFNgEiG4cJQ/Christina-Le---Ajax-Project?node-id=1%3A4

![Screen Shot 2022-03-03 at 12 51 18 AM](https://user-images.githubusercontent.com/97194651/156530843-56041b84-ee1d-4107-b3b3-609e352a76a3.png)

![Screen Shot 2022-03-03 at 12 49 13 AM](https://user-images.githubusercontent.com/97194651/156530863-f7ef1836-1897-4ba0-a1c5-57d44b0f0159.png)

![Screen Shot 2022-03-03 at 12 49 21 AM](https://user-images.githubusercontent.com/97194651/156530879-e84f3f7d-8cb1-4677-81dd-33539d46290f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Link the starter files all together within the head of the index.html file
- [x] Add a ‘div[data-view=”product-lists”]’ to the html 
- [x] Add an empty unordered list to the ‘div[data-view=”product-lists”]’ element in the html
- [x] Add some dummy data product entries to the unordered list in the html and style them to match the wireframe 
- [x] Ensure that the product listings look good on both mobile and desktop screens 
- [x] Ensure that the public API works using the ‘HTTPie’ method and ‘XMLHttpRequest’ 
- [x] Create a function that takes a single product listing object and returns a DOM tree that matches one of the example entries in the HTML
- [x] Use a loop to create a DOM tree for each product listing in the data model and ‘append’ it to the page when the ‘‘’DOMContentLoaded’’’ event is fired
- [x] Remove the dummy data entries once the product listings have successfully appended to the DOM on page load.
- [x] Clean up all unnecessary styling
- [x] Test the app in private browsing mode
- [x] Fix all errors
