### ISSUE TITLE
User can view the details of the products they click

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/ajax-project#2]
## 📐 Functionality

Users will be able to select a product listing and view more information about it.

## 🖼️ Wireframes

Mobile:
https://www.figma.com/file/FygER9DI2JeIFNgEiG4cJQ/Christina-Le---Ajax-Project?node-id=1%3A3

Desktop:
https://www.figma.com/file/FygER9DI2JeIFNgEiG4cJQ/Christina-Le---Ajax-Project?node-id=1%3A4

![Screen Shot 2022-03-03 at 11 56 28 AM](https://user-images.githubusercontent.com/97194651/156642922-2fb4635a-d384-4aba-88b2-07728b4ec65d.png)

![Screen Shot 2022-03-01 at 10 59 10 AM](https://user-images.githubusercontent.com/97194651/156231726-9a973d49-b7fc-4703-9a84-8b61cb22bc6e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add a div[data-view="product-details"] to the HTML
- [x] Add a 'home' button in the nav bar
- [x] Give each product listing a data entry id 
- [x] Listen for ‘clicks’ on the parent element of all rendered product listings 
- [x] Show the product listing’s page [with its name, price, and description] if it gets clicked 
- [x] Ensure that the data entry id matches the product listings that was clicked
- [x] Ensure that 'home' button returns the user back to the home page when clicked
- [x] Clean up all unnecessary styling
- [x] Test the app in private browsing mode
- [x] Fix all errors
