### ISSUE TITLE
User can save the products they want to buy

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/ajax-project#3]
## 📐 Functionality

User will be able to save the products they are interested in/want to buy

## 🖼️ Wireframes

Mobile:
https://www.figma.com/file/FygER9DI2JeIFNgEiG4cJQ/Christina-Le---Ajax-Project?node-id=1%3A3

Desktop:
https://www.figma.com/file/FygER9DI2JeIFNgEiG4cJQ/Christina-Le---Ajax-Project?node-id=1%3A4

![Screen Shot 2022-03-07 at 3 45 13 PM](https://user-images.githubusercontent.com/97194651/157137314-4d8304da-bb48-411d-9681-efdc3175f2c3.png)

![Screen Shot 2022-03-07 at 3 45 25 PM](https://user-images.githubusercontent.com/97194651/157137333-94575b75-c6fa-4ab4-9c06-121f418b0aa4.png)

## ✅ Task List

- [x] Add a saved icon to the nav-bar
- [x] Below the description of the details page, add a save-button
- [x] Style the button to ensure that it looks good on both mobile and desktop 
- [x] Ensure that the local storage is saving the product listing when clicked
- [x] Clean up any styling
- [x] Test in private browsing mode
- [x] Fix all errors
