### ISSUE TITLE
User can view saved products

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/ajax-project#4]
## 📐 Functionality

User will be able to view their saved products

## 🖼️ Wireframes

Mobile:
https://www.figma.com/file/FygER9DI2JeIFNgEiG4cJQ/Christina-Le---Ajax-Project?node-id=1%3A3

Desktop:
https://www.figma.com/file/FygER9DI2JeIFNgEiG4cJQ/Christina-Le---Ajax-Project?node-id=1%3A4

![Screen Shot 2022-03-09 at 10 08 02 AM](https://user-images.githubusercontent.com/97194651/157511384-766b93aa-597e-4493-9cee-e57bb01878af.png)
![Screen Shot 2022-03-09 at 10 08 20 AM](https://user-images.githubusercontent.com/97194651/157511392-46a0e02c-4640-42a8-b1a3-78b024374b69.png)

## ✅ Task List

- [x] Change ‘Beauty List’ header to ‘Saved Items’ header
- [x] Add an event listener for the saved icon
- [x] Ensure that when a user saves a product, it’ll take them to the saved page
- [x] Ensure that saved page contains saved products
- [x] Add refresh condition that keeps user on current page after refresh
- [x] Clean up any styling
- [x] Test in private browsing mode
- [x] Fix all errors
